filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
  include_containers:
    - name: 'elasticsearch'
    - name: 'logstash'

output.logstash:
  hosts: ["logstash:5044"]

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"

